export const newOptionData = {
  isEditable: true,
  beforeWorkCondition: {
    id: 1,
    transportationMethod: 3,
    pyeong: 33,
  },
  afterWorkCondition: {
    id: 2,
    transportationMethod: 0,
    pyeong: 40,
  },
  livingService: {
    movingCleaningService: {
      id: 1,
      serviceName: "입주청소서비스",
      serviceType: 1,
      serviceTypeName: "VIP",
      serviceRequestDate: "20240305",
      servicePayment: 1000000,
      selected: true,
      selectedType: 0,
      serviceList: [
        {
          serviceType: 0,
          serviceTypeName: "일반",
        },
        {
          serviceType: 1,
          serviceTypeName: "VIP",
        },
      ],
      paymentMethod: 1,
    },
    deodorizationService: {
      id: 2,
      serviceName: "탈취살균서비스",
      serviceRequestDate: "",
      servicePayment: 100000,
      selected: false,
      paymentMethod: 0,
    },
    organizationStorageService: {
      id: 3,
      serviceName: "정리수납서비스",
      serviceRequestDate: "20240307",
      servicePayment: 120000,
      selected: true,
      paymentMethod: 3,
    },
  },
  optionService: [
    {
      id: 1,
      optionType: 1,
      optionName: "일반 장롱",
      optionNameEng: "Normal Wardrobe",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 2,
      optionType: 2,
      optionName: "슬라이드 장롱",
      optionNameEng: "Slide Wardrobe",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 3,
      optionType: 3,
      optionName: "벽걸이 TV",
      optionNameEng: "Wall-mounted TV",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 4,
      optionType: 4,
      optionName: "에어컨",
      optionNameEng: "Air Conditioner",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 5,
      optionType: 5,
      optionName: "냉장고",
      optionNameEng: "refrigerator",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 6,
      optionType: 6,
      optionName: "소파",
      optionNameEng: "Sofa",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 7,
      optionType: 7,
      optionName: "돌침대(싱글)",
      optionNameEng: "Single Bed",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 8,
      optionType: 8,
      optionName: "돌침대(더블)",
      optionNameEng: "Double Bed",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 9,
      optionType: 9,
      optionName: "책상/책장 세트",
      optionNameEng: "Set of Desk",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 10,
      optionType: 10,
      optionName: "시스템 행거",
      optionNameEng: "System Hanger",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 11,
      optionType: 11,
      optionName: "금고",
      optionNameEng: "Safe",
      optionPayment: 0,
      selected: false,
    },
  ],
};
