export const newOptionData = {
  success: true,
  receiptOptionData: {
    isEditable: true,
    beforeWorkCondition: {
      id: 1,
      transportationMethod: 0,
      pyeong: 0,
    },
    afterWorkCondition: {
      id: 2,
      transportationMethod: 0,
      pyeong: 0,
    },
    ladderTruck: {
      id: 3,
      servicePayment: 0,
      selected: false,
    },
    livingService: {
      movingCleaningService: {
        id: 1,
        serviceName: "입주청소서비스",
        serviceRequestDate: "",
        servicePayment: 0,
        selected: false,
        paymentMethod: 0,
        selectedType: 0,
        serviceList: [
          {
            serviceType: 0,
            serviceTypeName: "일반",
            itemCd: "P01144",
          },
          {
            serviceType: 1,
            serviceTypeName: "VIP",
            itemCd: "P00316",
          },
        ],
      },
      electronicCleaningService: {
        id: 2,
        serviceName: "가전청소서비스",
        serviceRequestDate: "",
        servicePayment: 0,
        selected: false,
        paymentMethod: 0,
        selectedType: 0,
        serviceList: [
          {
            serviceType: 0,
            serviceTypeName: "가전청소-에어컨",
            itemCd: "P01478",
          },
          {
            serviceType: 1,
            serviceTypeName: "가전청소-세탁기",
            itemCd: "P01479",
          },
        ],
      },
      organizationStorageService: {
        id: 3,
        serviceName: "정리수납서비스",
        serviceRequestDate: "",
        servicePayment: 0,
        selected: false,
        paymentMethod: 0,
        selectedType: 0,
        serviceList: [
          {
            serviceType: 0,
            serviceTypeName: "일반",
            itemCd: "P01143",
          },
          {
            serviceType: 1,
            serviceTypeName: "VIP",
            itemCd: "P01055",
          },
        ],
      },
      deodorizationService: {
        id: 4,
        serviceName: "탈취살균(새집증후군)서비스",
        serviceRequestDate: "",
        servicePayment: 0,
        selected: false,
        paymentMethod: 0,
        itemCd: "P01261",
      },
      apronService: {
        id: 5,
        serviceName: "에이프런서비스",
        serviceRequestDate: "",
        servicePayment: 0,
        selected: false,
        paymentMethod: 0,
        itemCd: "P00311",
      },
      movjetService: {
        id: 6,
        serviceName: "무브제 디렉터 상담",
        serviceRequestDate: "",
        servicePayment: 0,
        selected: false,
        paymentMethod: 0,
        itemCd: "P00489",
      },
      otherService: {
        id: 7,
        serviceName: "기타서비스",
        serviceRequestDate: "",
        servicePayment: 0,
        selected: false,
        paymentMethod: 0,
        description: "",
        itemCd: "P00489",
      },
    },
    optionService: {
      selected: false,
      ServiceList: [
        {
          id: 1,
          itemCd: "P01467",
          installation: false,
          decomposition: false,
          optionType: 1,
          optionName: "일반 장롱",
          optionNameEng: "Normal Wardrobe",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 2,
          itemCd: "P01468",
          installation: false,
          decomposition: false,
          optionType: 2,
          optionName: "슬라이드 장롱",
          optionNameEng: "Slide Wardrobe",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 3,
          itemCd: "P01476",
          installation: false,
          decomposition: false,
          optionType: 3,
          optionName: "시스템 행거",
          optionNameEng: "System Hanger",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 4,
          itemCd: "P01475",
          installation: false,
          decomposition: false,
          optionType: 4,
          optionName: "책상/책장 세트",
          optionNameEng: "Set of Desk",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 5,
          itemCd: "P01469",
          installation: false,
          decomposition: false,
          optionType: 5,
          optionName: "벽걸이 TV",
          optionNameEng: "Wall-mounted TV",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 6,
          itemCd: "P01470",
          installation: false,
          decomposition: false,
          optionType: 6,
          optionName: "에어컨",
          optionNameEng: "Air Conditioner",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 7,
          itemCd: "P01471",
          installation: false,
          decomposition: false,
          optionType: 7,
          optionName: "정수기/냉장고",
          optionNameEng: "refrigerator",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 8,
          itemCd: "P01473",
          installation: false,
          decomposition: false,
          optionType: 8,
          optionName: "돌침대(싱글)",
          optionNameEng: "Single Bed",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 9,
          itemCd: "P01474",
          installation: false,
          decomposition: false,
          optionType: 9,
          optionName: "돌침대(더블)",
          optionNameEng: "Double Bed",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 10,
          itemCd: "P01477",
          installation: false,
          decomposition: false,
          optionType: 10,
          optionName: "금고",
          optionNameEng: "Safe",
          optionPayment: 0,
          selected: false,
        },
        {
          id: 11,
          itemCd: "P00489",
          installation: false,
          decomposition: false,
          optionType: 11,
          optionName: "기타",
          optionNameEng: "ETC",
          optionPayment: 0,
          selected: false,
        },
      ],
    },
  },
};
