export const realOptionData = {
  isEditable: true,
  beforeWorkCondition: {
    id: 1,
    transportationMethod: 0,
    pyeong: 0,
  },
  afterWorkCondition: {
    id: 2,
    transportationMethod: 0,
    pyeong: 0,
  },
  ladderTruck: {
    id: 3,
    servicePayment: 0,
    selected: false,
  },
  livingService: {
    movingCleaningService: {
      id: 1,
      serviceName: "입주청소서비스",
      serviceRequestDate: "",
      servicePayment: 0,
      selected: false,
      selectedType: 0,
      serviceList: [
        {
          serviceType: 0,
          serviceTypeName: "일반",
          itemCd: "P01144",
        },
        {
          serviceType: 1,
          serviceTypeName: "VIP",
          itemCd: "P00316",
        },
      ],
    },
    deodorizationService: {
      id: 2,
      serviceName: "탈취살균서비스",
      serviceRequestDate: "",
      servicePayment: 0,
      selected: false,
      paymentMethod: 0,
      itemCd: "P01261",
    },
    organizationStorageService: {
      id: 3,
      serviceName: "정리수납서비스",
      serviceRequestDate: "",
      servicePayment: 0,
      selected: false,
      paymentMethod: 0,
      itemCd: "P01056",
    },
    otherService: {
      id: 4,
      serviceName: "기타서비스",
      serviceRequestDate: "",
      servicePayment: 0,
      selected: false,
      paymentMethod: 0,
      description: "",
      itemCd: "",
    },
  },
  optionService: [
    {
      id: 1,
      itemCd: "",
      optionType: 1,
      optionName: "일반 장롱",
      optionNameEng: "Normal Wardrobe",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 2,
      itemCd: "",
      optionType: 2,
      optionName: "슬라이드 장롱",
      optionNameEng: "Slide Wardrobe",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 3,
      itemCd: "",
      optionType: 3,
      optionName: "벽걸이 TV",
      optionNameEng: "Wall-mounted TV",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 4,
      itemCd: "",
      optionType: 4,
      optionName: "에어컨",
      optionNameEng: "Air Conditioner",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 5,
      itemCd: "",
      optionType: 5,
      optionName: "냉장고",
      optionNameEng: "refrigerator",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 6,
      itemCd: "",
      optionType: 6,
      optionName: "소파",
      optionNameEng: "Sofa",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 7,
      itemCd: "",
      optionType: 7,
      optionName: "돌침대(싱글)",
      optionNameEng: "Single Bed",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 8,
      itemCd: "",
      optionType: 8,
      optionName: "돌침대(더블)",
      optionNameEng: "Double Bed",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 9,
      itemCd: "",
      optionType: 9,
      optionName: "책상/책장 세트",
      optionNameEng: "Set of Desk",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 10,
      itemCd: "",
      optionType: 10,
      optionName: "시스템 행거",
      optionNameEng: "System Hanger",
      optionPayment: 0,
      selected: false,
    },
    {
      id: 11,
      itemCd: "",
      optionType: 11,
      optionName: "금고",
      optionNameEng: "Safe",
      optionPayment: 0,
      selected: false,
    },
  ],
};
